-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS c22391076_dw.dim_customer
(
    customer_key bigint NOT NULL,
    region text COLLATE pg_catalog."default",
    full_name text COLLATE pg_catalog."default",
    age_band text COLLATE pg_catalog."default",
    CONSTRAINT dim_customer_pkey PRIMARY KEY (customer_key)
);

CREATE TABLE IF NOT EXISTS c22391076_dw.dim_date
(
    date_key integer NOT NULL,
    date_actual date,
    year integer,
    month integer,
    day integer,
    CONSTRAINT dim_date_pkey PRIMARY KEY (date_key)
);

CREATE TABLE IF NOT EXISTS c22391076_dw.dim_product
(
    product_key bigint NOT NULL,
    category text COLLATE pg_catalog."default",
    merchant text COLLATE pg_catalog."default",
    price numeric(12, 2),
    CONSTRAINT dim_product_pkey PRIMARY KEY (product_key)
);

CREATE TABLE IF NOT EXISTS c22391076_dw.fact_sales
(
    fact_id serial NOT NULL,
    date_key integer,
    customer_key bigint,
    product_key bigint,
    quantity integer,
    unit_price numeric(12, 2),
    discount numeric(12, 2),
    total numeric(12, 2),
    meta jsonb,
    CONSTRAINT fact_sales_pkey PRIMARY KEY (fact_id)
);

CREATE UNLOGGED TABLE IF NOT EXISTS c22391076_dw.temp_factsales
(
    fact_id integer,
    date_key integer,
    customer_key bigint,
    product_key bigint,
    quantity integer,
    unit_price numeric(12, 2),
    discount numeric(12, 2),
    total numeric(12, 2),
    meta jsonb
);

CREATE TABLE IF NOT EXISTS dw_lite.dim_customer
(
    customer_key bigint NOT NULL,
    region text COLLATE pg_catalog."default",
    full_name text COLLATE pg_catalog."default",
    age_band text COLLATE pg_catalog."default",
    CONSTRAINT dim_customer_pkey PRIMARY KEY (customer_key)
);

CREATE TABLE IF NOT EXISTS dw_lite.dim_date
(
    date_key integer NOT NULL,
    date_actual date,
    year integer,
    month integer,
    day integer,
    CONSTRAINT dim_date_pkey PRIMARY KEY (date_key)
);

CREATE TABLE IF NOT EXISTS dw_lite.dim_product
(
    product_key bigint NOT NULL,
    category text COLLATE pg_catalog."default",
    merchant text COLLATE pg_catalog."default",
    price numeric(12, 2),
    CONSTRAINT dim_product_pkey PRIMARY KEY (product_key)
);

CREATE TABLE IF NOT EXISTS dw_lite.fact_sales
(
    fact_id serial NOT NULL,
    CONSTRAINT fact_sales_pkey PRIMARY KEY (fact_id)
);

CREATE TABLE IF NOT EXISTS rel_src.categories
(
    category_id serial NOT NULL,
    parent_id integer,
    category_name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS rel_src.customers
(
    customer_id bigserial NOT NULL,
    region_id smallint NOT NULL,
    full_name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id),
    CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS rel_src.events
(
    event_id bigserial NOT NULL,
    customer_id bigint,
    session_id uuid NOT NULL DEFAULT gen_random_uuid(),
    event_ts timestamp with time zone NOT NULL DEFAULT now(),
    event_type text COLLATE pg_catalog."default" NOT NULL,
    payload jsonb NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS rel_src.merchants
(
    merchant_id bigserial NOT NULL,
    merchant_name text COLLATE pg_catalog."default" NOT NULL,
    region_id smallint NOT NULL,
    CONSTRAINT merchants_pkey PRIMARY KEY (merchant_id)
);

CREATE TABLE IF NOT EXISTS rel_src.order_items
(
    order_id bigint NOT NULL,
    item_no integer NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    discount numeric(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_id, item_no)
);

CREATE TABLE IF NOT EXISTS rel_src.orders
(
    order_id bigserial NOT NULL,
    customer_id bigint NOT NULL,
    merchant_id bigint NOT NULL,
    order_ts timestamp with time zone NOT NULL,
    order_date date,
    status text COLLATE pg_catalog."default" NOT NULL,
    total_amount numeric(14, 2) NOT NULL,
    meta jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS rel_src.products
(
    product_id bigserial NOT NULL,
    category_id integer,
    merchant_id bigint,
    sku text COLLATE pg_catalog."default" NOT NULL,
    product_name text COLLATE pg_catalog."default" NOT NULL,
    base_price numeric(12, 2) NOT NULL,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT products_pkey PRIMARY KEY (product_id),
    CONSTRAINT products_sku_key UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS rel_src.regions
(
    region_id smallserial NOT NULL,
    region_code text COLLATE pg_catalog."default" NOT NULL,
    region_name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT regions_pkey PRIMARY KEY (region_id),
    CONSTRAINT regions_region_code_key UNIQUE (region_code)
);

ALTER TABLE IF EXISTS c22391076_dw.fact_sales
    ADD CONSTRAINT fact_sales_customer_key_fkey FOREIGN KEY (customer_key)
    REFERENCES c22391076_dw.dim_customer (customer_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS c22391076_dw.fact_sales
    ADD CONSTRAINT fact_sales_date_key_fkey FOREIGN KEY (date_key)
    REFERENCES c22391076_dw.dim_date (date_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS c22391076_dw.fact_sales
    ADD CONSTRAINT fact_sales_product_key_fkey FOREIGN KEY (product_key)
    REFERENCES c22391076_dw.dim_product (product_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rel_src.categories
    ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES rel_src.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS rel_src.customers
    ADD CONSTRAINT customers_region_id_fkey FOREIGN KEY (region_id)
    REFERENCES rel_src.regions (region_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS customers_region_id_idx
    ON rel_src.customers(region_id);


ALTER TABLE IF EXISTS rel_src.events
    ADD CONSTRAINT events_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES rel_src.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS events_customer_idx
    ON rel_src.events(customer_id);


ALTER TABLE IF EXISTS rel_src.merchants
    ADD CONSTRAINT merchants_region_id_fkey FOREIGN KEY (region_id)
    REFERENCES rel_src.regions (region_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rel_src.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES rel_src.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS rel_src.order_items
    ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES rel_src.products (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS order_items_product_id_idx
    ON rel_src.order_items(product_id);


ALTER TABLE IF EXISTS rel_src.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES rel_src.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS orders_customer_id_idx
    ON rel_src.orders(customer_id);


ALTER TABLE IF EXISTS rel_src.orders
    ADD CONSTRAINT orders_merchant_id_fkey FOREIGN KEY (merchant_id)
    REFERENCES rel_src.merchants (merchant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS orders_merchant_id_idx
    ON rel_src.orders(merchant_id);


ALTER TABLE IF EXISTS rel_src.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES rel_src.categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS rel_src.products
    ADD CONSTRAINT products_merchant_id_fkey FOREIGN KEY (merchant_id)
    REFERENCES rel_src.merchants (merchant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;